### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by gregroberts** [asmuth/fviz#223]
Are there pre-compiled binaries anywhere? It says in the docs this would be coming in Dec-14, but I acn't find any links anywhere.

**Comment by cdolan92** [comment]
Also do not see any binaries, I'm assuming they are not out yet?

**Comment by morenoh149** [comment]
they were promised a while ago. http://fnordmetric.io/documentation/installation/ is the project active? need help @paulasmuth

**Comment by jonlil** [comment]
also wondering

**Comment by jachinte** [comment]
Last commit activity was 10 months ago, and no issue has been commented this year. I'm assuming this project is not actively developed.

**Comment by morenoh149** [comment]
actually I got an email from the author a while back

> So FnordMetric... As you probably noted the public github repo hasn't seen any changes in months. The project is far from dead though! In 2015 I raised a tiny seed round and started a company around the project. We've been working on making it into something much bigger for almost a year now...

> All the new code will also be 100% open-source. We haven't really launched yet, but you can get a sneak preview here http://maglev.io/maglevdb [the site isn't 100% finished yet though].

> So... Our company is selling consulting service around the product and also a hosted/cloud version. As we are still in a very early phase of the company we're open to helping out for free (at our own cost in the case of hosted services) to collect some references and beta users. Our current customers include one of the largest ecommerce sites in europe and one of the world's largest online publishers. 

I'd encourage you all to reach out and join their beta at paulasmuth@googlemail.com

**Comment by jachinte** [comment]
That's really nice! I noticed he was working in something but I thought it wasn't going to be open source. Thanks for letting us know @morenoh149

**Comment by paulasmuth** [comment]
So... I'm really excited to announce today we're finally releasing! :) We've been working on it for the last 2 years and haven't shown it to a lot of people yet, so honest/blunt feedback would be highly appreciated! https://github.com/eventql/eventql -- http://eventql.io/

**Comment by morenoh149** [comment]
@paulasmuth you need a tweet button :)

**Comment by paulasmuth** [comment]
@morenoh149  done :)
