### ISSUE TITLE
mysql_real_connect() failed: Access denied for user 'root'@'HOST 

### ISSUE THREAD

**Issue by Jonovono** [asmuth/fviz#224]
Hi. I am trying to connect to a remote mysql db (on Google cloud sql).

I do this:

```
IMPORT TABLE user FROM 'mysql://HOST3306/DB?    username=root&password=PASSWORD';
SELECT * FROM user;
```

But then I get the error:

```
mysql_real_connect() failed: Access denied for user   'root'@'DIFFERENTHOSTFROMABOVE' (using password: YES) while executing query: IMPORT TABLE user FROM 'mysql://HOST:3306/DB?  username=root&password=PASSWORD'; SELECT * FROM user;
```

When I run

```
mysql -u gae -p -h HOST
```

In the terminal it connects fine.

I am on Yosemite.

**Comment by fliiiix** [comment]
Not sure but 

> Access denied for user   'root'

Here is the user root and here 

> mysql -u gae 

its gae 

So maybe trie something like 

> mysql -u root -p -h HOST

**Comment by Jonovono** [comment]
Oops. It also works if I use user gae in fnordmetric
