### ISSUE TITLE
Fail to compile install chartsql on centos6.7 x64

### ISSUE THREAD

**Issue by wangxr1985** [asmuth/fviz#234]
When I download the source code, change the directory to  fnordmetric/fnordmetric-core and run make,I meet the following error message,and I don't know where to download the binary release.

(cd ../fnordmetric-webui && make)
make[1]: Entering directory `/root/fnordmetric-master/fnordmetric-webui'
make[1]: Leaving directory`/root/fnordmetric-master/fnordmetric-webui'
(cd build/cmake && make)
make[1]: Entering directory `/root/fnordmetric-master/fnordmetric-core/build/cmake'
./assets.sh
mkdir -p target/tests
mkdir -p stage/src
test -e stage/src/fnordmetric || ln -s ../../../../src stage/src/fnordmetric || true
(cd target && cmake .. -DCMAKE_BUILD_TYPE=Release && make)
-- MySQL Include dir: /usr/include/mysql  library dir: /usr/lib64/mysql
-- MySQL client libraries: mysqlclient_r
-- Could NOT find PostgreSQL (missing:  PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR PostgreSQL_TYPE_INCLUDE_DIR) 
WARNING: libpq not found, FnordMetric will be compiled without Postgres support
-- Configuring done
-- Generating done
-- Build files have been written to: /root/fnordmetric-master/fnordmetric-core/build/cmake/target
make[2]: Entering directory`/root/fnordmetric-master/fnordmetric-core/build/cmake/target'
make[3]: Entering directory `/root/fnordmetric-master/fnordmetric-core/build/cmake/target'
make[4]: Entering directory`/root/fnordmetric-master/fnordmetric-core/build/cmake/target'
Scanning dependencies of target fnordmetric-cli
make[4]: Leaving directory `/root/fnordmetric-master/fnordmetric-core/build/cmake/target'
make[4]: Entering directory`/root/fnordmetric-master/fnordmetric-core/build/cmake/target'
[  0%] Building CXX object CMakeFiles/fnordmetric-cli.dir/stage/src/fnordmetric/cli/cli.cc.o
In file included from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/flagparser.h:15,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/environment.h:13,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.cc:13:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/util/runtimeexception.h:62: error: ‘nullptr’ was not declared in this scope
In file included from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/util/logger.h:12,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/environment.h:14,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.cc:13:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/util/datetime.h:50: error: only declarations of constructors can be ‘explicit’
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/util/datetime.h:56: error: only declarations of constructors can be ‘explicit’
In file included from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.h:13,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.cc:14:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/util/outputstream.h:88: error: expected ‘;’ before ‘override’
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/util/outputstream.h:90: error: expected ‘;’ before ‘override’
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/util/outputstream.h:121: error: expected ‘;’ before ‘override’
In file included from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/runtime.h:17,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/query.h:17,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/queryservice.h:12,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.h:15,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.cc:14:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h: In member function ‘fnordmetric::query::Token\* fnordmetric::query::Parser::expectAndConsume(fnordmetric::query::Token::kTokenType)’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h:137: error: ‘nullptr’ was not declared in this scope
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h: In member function ‘fnordmetric::query::Token\* fnordmetric::query::Parser::expectAndConsume(const std::vector<fnordmetric::query::Token::kTokenType, std::allocator<fnordmetric::query::Token::kTokenType> >&)’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h:142: error: expected initializer before ‘:’ token
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h:166: error: expected primary-expression at end of input
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h:166: error: expected ‘;’ at end of input
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h:166: error: expected primary-expression at end of input
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h:166: error: expected ‘)’ at end of input
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h:166: error: expected statement at end of input
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h:166: error: expected ‘}’ at end of input
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h: In member function ‘fnordmetric::query::ASTNode\* fnordmetric::query::Parser::expectAndConsumeValueExpr()’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/parser/parser.h:171: error: ‘nullptr’ was not declared in this scope
In file included from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/queryplan.h:16,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/runtime.h:19,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/query.h:17,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/queryservice.h:12,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.h:15,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.cc:14:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/queryplannode.h: At global scope:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/queryplannode.h:36: error: expected ‘;’ before ‘override’
In file included from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/runtime.h:20,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/query.h:17,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/queryservice.h:12,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.h:15,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.cc:14:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/queryplanbuilder.h:64: error: expected ‘;’ before ‘override’
In file included from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/query.h:17,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/queryservice.h:12,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.h:15,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.cc:14:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/runtime.h:45: error: cannot declare field ‘fnordmetric::query::Runtime::query_plan_builder_’ to be of abstract type ‘fnordmetric::query::QueryPlanBuilder’
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/queryplanbuilder.h:52: note:   because the following virtual functions are pure within ‘fnordmetric::query::QueryPlanBuilder’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/queryplanbuilder.h:43: note:    virtual fnordmetric::query::QueryPlanNode\* fnordmetric::query::QueryPlanBuilderInterface::buildQueryPlan(fnordmetric::query::ASTNode_, fnordmetric::query::TableRepository_)
In file included from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql_extensions/drawstatement.h:17,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/query.h:19,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/queryservice.h:12,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.h:15,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.cc:14:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:74: error: expected ‘;’ before ‘override’
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.cc:215: error: expected ‘;’ at end of input
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.cc:215: error: expected ‘}’ at end of input
In file included from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql_extensions/drawstatement.h:17,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/query.h:19,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/query/queryservice.h:12,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.h:15,
                 from /root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/cli/cli.cc:14:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h: In constructor ‘fnordmetric::query::ResultList::ResultList(fnordmetric::query::ResultList&&)’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:29: error: class ‘fnordmetric::query::ResultList’ does not have any field named ‘columns_’
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:29: error: ‘class fnordmetric::query::ResultList’ has no member named ‘columns_’
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:30: error: class ‘fnordmetric::query::ResultList’ does not have any field named ‘rows_’
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:30: error: ‘class fnordmetric::query::ResultList’ has no member named ‘rows_’
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h: In member function ‘size_t fnordmetric::query::ResultList::getNumColumns() const’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:33: error: ‘columns_’ was not declared in this scope
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h: In member function ‘size_t fnordmetric::query::ResultList::getNumRows() const’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:37: error: ‘rows_’ was not declared in this scope
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h: In member function ‘const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >& fnordmetric::query::ResultList::getRow(size_t) const’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:41: error: ‘rows_’ was not declared in this scope
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:45: error: ‘rows_’ was not declared in this scope
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h: In member function ‘const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >& fnordmetric::query::ResultList::getColumns() const’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:49: error: ‘columns_’ was not declared in this scope
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h: In member function ‘int fnordmetric::query::ResultList::getColumnIndex(const std::string&) const’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:53: error: ‘columns_’ was not declared in this scope
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h: In member function ‘void fnordmetric::query::ResultList::addHeader(const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:63: error: ‘columns_’ was not declared in this scope
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h: In member function ‘void fnordmetric::query::ResultList::addRow()’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:67: error: ‘rows_’ was not declared in this scope
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h: In member function ‘void fnordmetric::query::ResultList::addColumn(const std::string&)’:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:71: error: ‘rows_’ was not declared in this scope
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h: At global scope:
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:72: error: expected unqualified-id at end of input
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:72: error: expected ‘}’ at end of input
/root/fnordmetric-master/fnordmetric-core/build/cmake/stage/src/fnordmetric/sql/runtime/resultlist.h:72: error: expected ‘}’ at end of input
make[4]: **\* [CMakeFiles/fnordmetric-cli.dir/stage/src/fnordmetric/cli/cli.cc.o] Error 1
make[4]: Leaving directory `/root/fnordmetric-master/fnordmetric-core/build/cmake/target'
make[3]: *** [CMakeFiles/fnordmetric-cli.dir/all] Error 2
make[3]: Leaving directory`/root/fnordmetric-master/fnordmetric-core/build/cmake/target'
make[2]: **\* [all] Error 2
make[2]: Leaving directory `/root/fnordmetric-master/fnordmetric-core/build/cmake/target'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/root/fnordmetric-master/fnordmetric-core/build/cmake'
make: **\* [build] Error 2

**Comment by whughchen** [comment]
ON CentOS 6.6 the same error

**Comment by waledmarp** [comment]
Confirmed, error CentOS 6.7 (Final) as stated by wangxr1985
