### ISSUE TITLE
fnordmetric 1.0.0: Running on heroku, websockets vs polling.

### ISSUE THREAD

**Issue by radiospiel** [asmuth/fviz#90]
fnordmetric really is awesome, and looks great on my local machine. However, I have trouble deploying it to heroku (and even though I haven't tried that yet, probably to other servers where it would run behind an nginx proxy.) 

Apparently fnordmetric 1.0.0 uses websockets as a transport, where 0.7.x polled the server. If I understand this issue correctly https://github.com/imanel/websocket-rack/issues/8 running websockets on heroku just does not work. 

Is there a simple way to fall back to polling instead of websockets? Some configuration option one can set somewhere? A working project 

I am aware that #73 already deals with running on heroku. The suggested soultion works, but with fnordmetric 0.7.x versions only.

**Comment by radiospiel** [comment]
@asmuth chops for fviz, which looks promising. I am still surprised though that fnordmetric issues have been folded into here. (Still, without the notification I would probably never have heard of fviz)

**Comment by asmuth** [comment]
Yes, the user interface really changed quite a bit in the last 8 years with one breaking change in 2014 and another one quite recently. One problem with that was that when you googled for "fnordmetric", you would overwhelmingly find blog posts and documentation for outdated versions, which would be super confusing to anybody using the recent versions from github.

So I figure that changing the name was the best thing to do. BTW, the "f" in fviz stands for fnord :) Also we'll make sure to create a branch with the older version of the code -- if somebody needs support for that, I'll happily provide it!

All the best greetings to Berlin!
